import { IHttpStatus } from '../services/interfaces';

const statusHttp: IHttpStatus[] = [
  { value: 100, name: 'O gato que só está passando.' },
  { value: 101, name: 'O gato da mudança.' },
  { value: 102, name: 'Parece ruim, mas nada aconteceu... Ainda.' },
  { value: 103, name: 'O gato cabeça;' },
  { value: 200, name: 'O gato que deu certo!' },
  { value: 201, name: 'O gato que cumpriu seu propósito!' },
  { value: 202, name: 'Tudo certo, mas ainda não deu em nada.' },
  { value: 203, name: 'Foi o que deu para fazer...' },
  { value: 204, name: 'Nada a declarar!' },
  { value: 205, name: 'Tempo de recomeçar!' },
  { value: 206, name: 'Calma que vem mais por aí...' },
  { value: 207, name: 'Na verdade não vim sozinho...' },
  { value: 300, name: 'Mamãe mandou eu escolher esse daqui...' },
  { value: 301, name: 'Não mora mais aqui.' },
  { value: 302, name: 'Recuperando-se de trauma.' },
  { value: 303, name: 'Não, esse é o gato do meu vizinho.' },
  { value: 304, name: 'Como nossos pais.' },
  { value: 305, name: 'Infelizmente você precisa ver um especialista!' },
  { value: 307, name: 'Saiu, mas deve voltar eventualmente.' },
  { value: 308, name: 'Na volta a gente compra.' },
  { value: 400, name: 'Como assim, desde quando eu sou um pet?' },
  { value: 401, name: 'Não mexa na barriga, Márcia!' },
  { value: 402, name: 'Não existe almoço grátis!' },
  { value: 403, name: 'Nunca mais vou misturar rações.' },
  { value: 404, name: 'Cadê o bebê?' },
  { value: 405, name: 'Somos vegetarianos!' },
  { value: 406, name: 'Eu já me lambi hoje, Márcia!' },
  { value: 407, name: 'Você pode me dar referências?' },
  { value: 408, name: 'Seu tempo acabou!' },
  { value: 409, name: 'Eu vou dar na sua cara!' },
  { value: 410, name: 'Oh, você queria?' },
  { value: 411, name: 'Será que eu consigo alcançar?' },
  { value: 412, name: 'É nítido que isso vai dar errado.' },
  { value: 413, name: 'Claro que eu vou caber aqui, humano!' },
  { value: 414, name: 'Muita informação!' },
  { value: 415, name: 'Não sei o que fazer com isso...' },
  { value: 416, name: 'Ainda estou com sede.' },
  { value: 417, name: 'Ops!' },
  { value: 418, name: 'Eu acho que eu vi um chazinho!' },
  { value: 420, name: 'Keep calm!' },
  { value: 421, name: 'Tranferindo você para um de nossos atendentes.' },
  { value: 422, name: 'Sim, estou ouvindo!' },
  { value: 423, name: 'Patas ao alto, você está preso!' },
  { value: 424, name: 'Algo de errado não está certo.' },
  { value: 425, name: 'Apenas mais 5 minutos...' },
  { value: 426, name: 'Eu acho que cresci, humano!' },
  { value: 429, name: 'Deixa eu te apresentar meus amigos...' },
  { value: 431, name: 'Há algo excessivo aqui, Márcia!' },
  { value: 444, name: 'Não quero falar com você.' },
  { value: 450, name: 'Não é o que você está pensando!' },
  { value: 451, name: 'Gostaria de não estar aqui.' },
  { value: 497, name: 'Sei que não posso fazer isso.' },
  { value: 498, name: 'Não aqui, humano!' },
  { value: 499, name: 'Essa porta já fechou!' },
  { value: 500, name: 'Você precisa desse fio, Márcia?' },
  { value: 501, name: 'Ainda não.' },
  { value: 502, name: 'Pegue-me se for capaz!' },
  { value: 503, name: 'Hora do cochilo.' },
  { value: 504, name: 'Onde você estava todo esse tempo,Márcia?!' },
  { value: 506, name: 'Não conheço esse pessoal aqui.' },
  { value: 507, name: 'A vida não me preparou para isso' },
  { value: 508, name: 'De novo, de novo, de novo!' },
  { value: 509, name: 'Aqui não dá mais!' },
  { value: 510, name: 'Falta alguma coisa...' },
  { value: 511, name: 'Como assim eu não posso passar?' },
  { value: 521, name: 'Nada para ver aqui!' },
  { value: 522, name: 'Para mim já deu, Márcia!' },
  { value: 523, name: 'Humano? Humano, cadê você?' },
  { value: 525, name: 'Opa, opa, que aqui tem diretoria!' },
  { value: 599, name: 'Um dos seus fios parece errado, Márcia!' },
];

export default statusHttp;
